---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - limitranges
  - namespaces
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubelease.io
  resources:
  - environmentleasepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.kubelease.io
  resources:
  - environmentleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubelease.io
  resources:
  - environmentleases/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kubelease.io
  resources:
  - environmentleases/status
  verbs:
  - get
  - patch
  - update
