apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-rolebinding
  labels:
    app.kubernetes.io/name: kubelease
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-role
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-token-reader
  namespace: system
  labels:
    app.kubernetes.io/name: kubelease
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-token-reader
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: system
