apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: system
  labels:
    app.kubernetes.io/name: kubelease
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: kustomize
