{{- if and .Values.controller.enabled .Values.controller.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubelease.controller.fullname" . }}
  labels:
    {{- include "kubelease.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubelease.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
{{- end }}
