{{- if and .Values.webhook.enabled (not .Values.webhook.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubelease.webhook.fullname" . }}-token
  labels:
    {{- include "kubelease.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
type: Opaque
stringData:
  token: change-me
  github-webhook-secret: change-me-github
{{- end }}
