## Append samples of your project ##
resources:
- platform_v1alpha1_environmentlease.yaml
- platform_v1alpha1_environmentlease_fixed.yaml
- platform_v1alpha1_environmentleasepolicy.yaml
- platform_v1alpha1_clustertarget_lease.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
