apiVersion: platform.kubelease.io/v1alpha1
kind: EnvironmentLease
metadata:
  name: fixed-name-demo
spec:
  ttl: 1h
  owner:
    name: ci
    team: platform
  namespace:
    name: kubelease-demo-preview
    labels:
      environment: preview
  quota:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  networkPolicy:
    defaultDeny: true
