apiVersion: platform.kubelease.io/v1alpha1
kind: EnvironmentLeasePolicy
metadata:
  labels:
    app.kubernetes.io/name: kubelease
    app.kubernetes.io/managed-by: kustomize
  name: preview-default
spec:
  ttl:
    default: 8h
    maximum: 72h
  idleTTL:
    default: 30m
    maximum: 2h
  quota:
    maxCPU: "4"
    maxMemory: 8Gi
  networkPolicy:
    defaultDenyRequired: true
